server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suldaksuldak?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  main:
    allow-bean-definition-overriding: 'true'

auth:
  kakao:
    code: c14c29936ab91bf8d5ff8ccf7ab0c06f
    redirect: http://localhost:8080/api/v1/oauth/kakao
    access_url: https://kauth.kakao.com/oauth/token